version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: scholarflow-db
    environment:
      POSTGRES_USER: scholarflow
      POSTGRES_PASSWORD: scholarflow
      POSTGRES_DB: scholarflow
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: